"""sec_step

Revision ID: 7694f357bbeb
Revises: f23ef31c9384
Create Date: 2024-09-21 10:04:50.256374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7694f357bbeb'
down_revision = 'f23ef31c9384'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
