"""first_step

Revision ID: f23ef31c9384
Revises: 5a94ef525b78
Create Date: 2024-09-21 10:01:38.849759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f23ef31c9384'
down_revision = '5a94ef525b78'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('database_name', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('host_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('yandex_lr',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Geo', sa.String(), nullable=False),
    sa.Column('Geoid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_config_association',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['config.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'config_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('username', sa.String(length=320), nullable=True),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('group_user_association',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'user_id')
    )
    op.create_table('list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('author', sa.Integer(), nullable=False),
    sa.Column('group', sa.Integer(), nullable=False),
    sa.Column('config', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['author'], ['user.id'], ),
    sa.ForeignKeyConstraint(['config'], ['config.id'], ),
    sa.ForeignKeyConstraint(['group'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('live_search_list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('author', sa.Integer(), nullable=False),
    sa.Column('main_domain', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['author'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_query_count',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('query_count', sa.Integer(), nullable=False),
    sa.Column('last_update_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('list_lr_search_system',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('lr', sa.Integer(), nullable=False),
    sa.Column('search_system', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['live_search_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('list_uri',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uri', sa.String(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('live_search_list_query',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['live_search_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('query_live_search_google',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('lr_list_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lr_list_id'], ['list_lr_search_system.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['query_id'], ['live_search_list_query.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('query_live_search_yandex',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('lr_list_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lr_list_id'], ['list_lr_search_system.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['query_id'], ['live_search_list_query.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('query_live_search_yandex')
    op.drop_table('query_live_search_google')
    op.drop_table('live_search_list_query')
    op.drop_table('list_uri')
    op.drop_table('list_lr_search_system')
    op.drop_table('user_query_count')
    op.drop_table('live_search_list')
    op.drop_table('list')
    op.drop_table('group_user_association')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('group_config_association')
    op.drop_table('yandex_lr')
    op.drop_table('roles')
    op.drop_table('group')
    op.drop_table('config')
    # ### end Alembic commands ###
